Create 16. Cache memory.md
MPSU/exAPS pull request #205
Opened 2023-09-24 21:13 UTC by TheDenison

Лекция 16. Кэш-память.

2023-09-24 21:33 UTC, HepoH3 reviewed
Вообще, выглядит очень круто. Я пока прошелся больше по форме, чем по содержанию. Но есть подозрение, что человек, который не в теме и в первый раз читает, мало что вынесет отсюда, попробую вбросить студентам этого года, у которых еще не было этой лекции, спрошу моменты которые были непонятны.

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +**Перед созданием Кэш-памяти нам нужно задаться 4-мя вопросами**:
Перед тем как задаться вопросами, нам нужно сперва вообще ввести определение кэш-памяти, иначе непонятно о чем вообще речь.

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Какие данные нужно заместить, при заполненной кэш-памяти? (<span style="color:rgb(255, 120, 0)">**Замещение строки**</span>)
Тут часто в скобках есть ссылки на какие-то строки, но опять же, сторонний читатель не поймет о чем речь.

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Какие данные нужно заместить, при заполненной кэш-памяти? (<span style="color:rgb(255, 120, 0)">**Замещение строки**</span>)
Вообще, изначально я думал, что то что в скобках, это названия подразделов, вот такой подход был бы прикольный. Мол ты в начале говоришь, что нужно решить 4 вопроса, и описываешь 4 подраздела, отвечающие на эти вопросы.

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +Порция перемещения данных между разными уровнями иерархии памяти._
Здесь либо пропущено подчеркивание в начале, либо лишнее в конце

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Каждый адрес в памяти отображается в <span style="color:rgb(255, 120, 0)">***один и тот же набор кэша***</span>
Здесь либо везде должны стоять в конце точки, либо нигде.

2023-09-24 21:33 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +![Пример анализа производительности](https://sun9-56.userapi.com/impg/6bGy7oHB9kk0ux7h2ctAwgLw5f6ZS3-2HhME2w/k2IoS2bP_tA.jpg?size=797x221&quality=96&sign=0be401cc8f22309d950e57264ee3cef3&type=album)
Тут пикча немного выбивается. Во-первых сперва кажется, будто это продолжение маркированного списка выше, но при этом он почему-то съехал.
Во-вторых, пример лучше наверное не делать в виде маркированного списка. Думаю лучше эту пикчу перегнать в markdown.

2023-09-24 22:57 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +![Пример анализа производительности](https://sun9-56.userapi.com/impg/6bGy7oHB9kk0ux7h2ctAwgLw5f6ZS3-2HhME2w/k2IoS2bP_tA.jpg?size=797x221&quality=96&sign=0be401cc8f22309d950e57264ee3cef3&type=album)
Да, я сперва хотел сделать полностью маркированным списком, но забыл что в MD есть нормальные таблицы, и попытался вписать пикчу. Исправлю

2023-09-24 22:59 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +Порция перемещения данных между разными уровнями иерархии памяти._
Стерлась в начале случайно

2023-09-24 23:10 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +* Каждый адрес в памяти отображается в <span style="color:rgb(255, 120, 0)">***один и тот же набор кэша***</span>
Поправлю

2023-09-25 00:24 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +* Какие данные нужно заместить, при заполненной кэш-памяти? (<span style="color:rgb(255, 120, 0)">**Замещение строки**</span>)
Изначально именно такая задумка у меня и была, но вылетело из головы. Добавлю ссылки с переходами

2023-09-25 03:33 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +**Перед созданием Кэш-памяти нам нужно задаться 4-мя вопросами**:
Расписал поподробнее

2023-09-25 07:39 UTC, HepoH3 requested changes
Все по-прежнему круто, единственное что меня смущает — это обилие html-тэгов. Обычно это моветон и желательно сильно на них не подсаживаться. Ты в каком-то редакторе пишешь, который за тебя форматирование делает? Просто ссылки на подразделы можно делать без `span id`, выделение жирным и курсивом без `<span style>`, пустые строки без `<div>`.
К `sub` и `sup` вопросов нет.

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +**Кэш-память** — это небольшой сегмент высокоскоростной памяти, обычно на базе SRAM(Static Random-Access Memory), расположенный непосредственно на процессоре или рядом с ним. Её главная функция — вре
```suggestion
**Кэш-память** — это небольшой сегмент высокоскоростной памяти, обычно на базе **SRAM** ([**Static Random-Access Memory**](../15.%20Memory.md), расположенный непосредственно на процессоре или рядом с ним. Её главная функция — временное хранение тех данных, к которым процессор часто обращается. Основная цель такой памяти — уменьшить задержку доступа к данным, служа мостом между процессором и основной оперативной памятью.
```

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +**Кэш-память** — это небольшой сегмент высокоскоростной памяти, обычно на базе SRAM(Static Random-Access Memory), расположенный непосредственно на процессоре или рядом с ним. Её главная функция — вре
Пока что этот документ пишется другим студентом, но в итоге здесь должна появиться лекция по памяти, в которой рассказывается и про SRAM тоже, будет неплохо сделать ссылку на место где про нее подробно рассказывается.

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +</div>
Видимо на пикче надо изменить текст с **hard drive** на **secondary memory**. Потому что hard drive — это hdd, a **secodary memory** — это внешняя память (hdd/ssd).

```suggestion
**Иерархия памяти** - это объединение разных типов памяти с целью получения большой, дешевой, и быстрой памяти. Наивысший уровень иерархии (**Cache**) обычно является наиболее быстрым и наименее емким, в то время как нижний уровень обычно имеет наибольший объем, но и наибольшую задержку (**Secondary (external) Memory**).

<div align="center">

![Иерархия памяти](https://github.com/MPSU/APS/assets/17159587/1fae137b-8b79-477c-87f2-4562c8330753)
</div>
```

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +Благодаря этим принципам локальности кэш-память может значительно повысить производительность системы, предварительно загружая и храня наиболее вероятные данные для последующих запросов.
Здесь сказано, что кэш загружает близлежащие данные благодаря пространственной локальности, но это не определение пространственной локальности (никто не скажет "пространственная локальность — это то, благодаря чему кэш загружает близлежащие данные").

Тут надо написать что пространственная и временная локальность — это наблюдения (закономерности), благодаря которым кэш-память вообще имеет место быть (если бы не эти закономерности, кэш-память была бы не эффективна). И дальше штука про "высокую вероятность", она в лекции прямо проговаривается.

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Что происходит при записи в кэш-память? (<span style="color:rgb(255, 120, 0)">**[Стратегия записи](#content9)**</span>)
Тут только работает content5.

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +_Количество места в кэш-памяти на которое притендует конкретная строка. Каждая ячейка может располагаться только в одном наборе, один набор может состоять из нескольких строк - это и есть степень асс
```suggestion
_Количество места в кэш-памяти на которое претендует конкретная строка. Каждая ячейка может располагаться только в одном наборе, один набор может состоять из нескольких строк - это и есть степень ассоциативности._
```

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +Мы сразу получаем порцию данных, если в кэше хранятся инструкции, то при обращении к первой инструкции,У нас автоматически подгружаются остальные 3 инструкции.
Во-первых, тут очепятка видимо в `"инструкции,У"`, во-вторых — тяжело читать этот поток сознания, надо разделить на пару предложений.

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +  *Рассмотрим на примере двухсекционного кэша, где у нас добавляется дополнительный бит (**U** - used) куда помещается номер секции, которая сейчас не использовалась. Т.е. если сейчас мы записываем в
```suggestion
  *Рассмотрим на примере двухсекционного кэша, где у нас добавляется дополнительный бит (**U** - used) куда помещается номер секции, которая сейчас не использовалась. Т.е. если сейчас мы записываем в секцию 0 то в этот бит попадает 1, и если потребуется какую то из ячеек убрать, то устройство управления этим кэшем, выберет ту ячейку, которая указана в поле U.*
```

2023-09-25 07:39 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Эклюзивный кэш.
```suggestion
* Эксклюзивный кэш.  
```

2023-09-25 08:26 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +Мы сразу получаем порцию данных, если в кэше хранятся инструкции, то при обращении к первой инструкции,У нас автоматически подгружаются остальные 3 инструкции.
Я тут параллельно пересматривал лекцию, и пропустил этот участок. Поправлю

2023-09-25 08:35 UTC, TheDenison commented on Lectures/16. Cache memory.md
> +* Что происходит при записи в кэш-память? (<span style="color:rgb(255, 120, 0)">**[Стратегия записи](#content9)**</span>)
По поводу нагромождение html тегов, в первой версии файла я делал цветные выделения текста, но гит обрезает все стили и их не видно. Если планируется использовать этот файл только в рамках Гита, я их удалю.

Касательно тегов span id, просто использовал то что первое эффективное и знакомое использовал, посмотрю попозже какие есть ещё вариации.

А по поводу тегов <div>, приходится оставлять пустое место специально, потому что форматирование съезжает без пустого пространства, и выглядит кривовато.

Использую редактор Atom, но сейчас решил перейти в WebStorm, из него проще взаимодействовать с гитом.

2023-09-25 08:49 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* Что происходит при записи в кэш-память? (<span style="color:rgb(255, 120, 0)">**[Стратегия записи](#content9)**</span>)
якоря можно делать прямо по названию заголовка. Пример:

```Markdown
## Очень сложный заголовок верхнего уровня

[здесь я ссылаюсь на сложный заголовок](#очень-сложный-заголовок-верхнего-уровня)
```

В атоме наверняка есть расширения для markdown (в VSCode есть расширение All in one), которое позволяет делать автогенерируемое оглавление, предлагает в виде сниппетов такие ссылки на разделы (сразу в правильном виде, чтоб не думать как надо их писать).

если нужно сделать много пустых строк, то дивом можно пользоваться, да.

И да, конспекты будут использоваться скорее всего чисто в рамках гитхаба, так что думаю лучше убрать избыточные тэги.

2023-09-27 07:55 UTC, HepoH3 requested changes
У тебя нет разделов второго уровня, в итоге ты съезжаешь аж до четвертого. Переписал два вводных раздела. Пройдись по оставшимся (начиная с кэша прямого отображения). Сейчас они не могут заменить то, что проговаривалось на лекции. Тут много картинок, но к этим картинкам нужны пояснения. Возможно даже иногда надо продублировать картинку, выделив какую-то её часть, где лектор водил мышкой и говорил что вот сюда кладутся данные.
А так, я думаю еще разок-другой дожать, и получится конфетка.

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
>  32-х битный адрес, основная память _memory_, 32-х битный адрес. Для примера у нас будет 8 наборов и длина строки будет одно слово.
Рассмотрим _рис. <номер рисунка (всем пикчам добавить подписи с нумерацией)>_. Здесь представлена основная память, имеющая 32-битный адрес. В этом примере кэш будет состоять из 8 наборов при длине строки, равной одному слову.

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +![](https://github.com/MPSU/APS/assets/17159587/1fae137b-8b79-477c-87f2-4562c8330753)
Я там изменил только верхний кусок, забыв что тут одна пикча, а не две.
```suggestion
![Иерархия памяти](https://github.com/MPSU/APS/assets/17159587/e3c10f2b-5cbe-4726-850c-f022ed4b5176)
```

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +### КЭШ-память
```suggestion
### Кэш-память
```

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +* [Основные оптимизации кэш-памяти](#Основные-оптимизации-кэш-памяти)
потом надо будет обновить под новые названия абзацев

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +Первые 2 бита (**Byte Offset**) - смещение
```suggestion
Первые 2 бита (**Byte Offset**) - смещение внутри слова
```

2023-09-27 07:55 UTC, HepoH3 commented on Lectures/16. Cache memory.md
>  **Длина строки (блока):**
Этот подраздел не входит в раздел полностью ассоциативного кэша (на пикче несколько наборов). Его надо в явном виде отделить.

2023-09-29 06:22 UTC, HepoH3 reviewed
И заголовки все третьего уровня вместо второго (надо ставить ## вместо ###). Ладно, правь это и давай к следующему конспекту перейдем, а в это время я скину студентам, чтоб они сказали какие места оказались непонятны.
Да, и нам будет удобней работать, если ты будешь нажимать кнопку вверху справа "request review" у моего ника. Так я буду понимать что ты закончил работу и ждешь от меня фидбека, а не просто сделал промежуточный коммит, потому что сейчас вот выглядит так будто ты не все сделал, но вроде бы дальше активности нет.
![firefox_vRIiHhYXeL](https://github.com/MPSU/APS/assets/17159587/a0522912-d67c-4503-8d28-f5347b43ed35)

2023-09-29 06:22 UTC, HepoH3 commented on Lectures/16. Cache memory.md
> +**Почему это важно?** Основываясь на принципах временной и пространственной локальности, можно проектировать алгоритмы и структуры данных, которые эффективно используют кэш и другие уровни иерархии п
Я убрал это предложение в своем коммите, потому что там тавтология и местами формулировки не слишком корректные.

2023-09-30 07:44 UTC, HepoH3 approved these changes
Я все ещё считаю, что виды кэша надо расписать подробней, но окей, давай пока что переключимся на следующий конспект, а этот я вброшу пока студентам этого года для получения фидбэка. Может за это время еще и лектор что-нибудь добавит.
А так, отличная работа, пока что мне этот конспект нравится больше всех остальных, так держать!

2023-10-04 05:35 UTC, HepoH3 approved these changes

2023-10-04 05:37 UTC, merged