Лекция 20: Ввод/вывод
MPSU/exAPS pull request #207
Opened 2023-09-29 19:56 UTC by MDamirM

2023-09-30 07:41 UTC, HepoH3 requested changes

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +К выделенным адресным пространствам относятся:
```suggestion
К выделенным адресным пространствам относятся такие, где:
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +![](../../ПМ/pictures/lecture20/pic5.png)
Ничего из этого не понятно, нужно пояснение

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Отдельная шина для системы ввода-вывода подключена к центральному процессору.
```suggestion
- Отдельная шина для системы ввода-вывода подключена к центральному процессору.

```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Отдельная шина для системы ввода-вывода подключена к центральному процессору.
Новая строка появится только если между абзацами будет пустая строка в md-файле, либо если в конце переноса добавить 2 пробела.

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Единая шина для системы ввода-вывода и основной памяти. (например RiscV)
```suggestion
- Единая шина для системы ввода-вывода и основной памяти. (например RISC-V)
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Минусы: програмисту сложнее разобраться в коде на Ассемблере.
```suggestion
Минусы: програмисту сложнее разобраться в коде в ассемблере. 
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Плюсы: В случае совместного мы имеем гибкий размер системы ввода-вывода (то есть мы можем уменьшить количество памяти и увеличить количество систем ввода-вывода или наоборот).
```suggestion
Плюсы: В случае совместного адресного пространства мы имеем гибкий размер системы ввода-вывода (то есть мы можем уменьшить количество памяти и увеличить количество систем ввода-вывода или наоборот).
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Контроллер прямого доступа к памяти -- это устройство, которое берет на себя задачу переброски информации из периферийных устройств в основную память либо наоборот из основной памяти в периферийное у
```suggestion
Контроллер прямого доступа к памяти — это устройство, которое берет на себя задачу переброски информации из периферийных устройств в основную память либо наоборот из основной памяти в периферийное устройство в обход процессора.
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Контроллер прямого доступа к памяти -- это устройство, которое берет на себя задачу переброски информации из периферийных устройств в основную память либо наоборот из основной памяти в периферийное у
Это не вк/телега с автозаменой `--`→`—`, тире надо писать ручками (alt+0151)

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +1. Периферийное устойство по специальной линии 'дергает' контроллер прямого доступа к памяти, что нужно передать данные в основную память.
делает запрос контроллеру о том что нужно передать

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Либо из центрального процессора либо из периферийного устройства (в зависимости от конфигурации системы) КПДП получит адрес, с которого начнется запись в основную память (в случае переброски информац
```suggestion
Либо из центрального процессора, либо из периферийного устройства (в зависимости от конфигурации системы) КПДП получит адрес, с которого начнется запись в основную память (в случае переброски информации из переферийных устройств в основную память).
```

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +2. [Ссылка](https://www.youtube.com/watch?v=R-a4zkZbPVo&list=PL0def37HEo5KMH7gONw_JnczvQJBv1EZL&index=20) на видеозапись лекции 2020 года.
а ссылка на запись 2020-го нужна? Если в конспекте не использовались, то думаю не зачем ее оставлять

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- RAID 6: RAID 5, у которого вдвое увеличено количество избыточных контрольных дисков, то есть 2 диска, в которых хранятся паритеты, что повышает надежность
Поскольку у тебя идут элементы маркированного списка из нескольких предложений, надо ставить точку в конце каждого элемента.

2023-09-30 07:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Системы вводы-вывода имеют отдельную шину управляющия, но шины адреса и данных совпадают с таковыми у памяти. (например x86)
```suggestion
- Системы вводы-вывода имеют отдельную шину управления, но шины адреса и данных совпадают с таковыми у памяти. (например x86)
```

2023-09-30 09:51 UTC, MDamirM commented on Lectures/20. Input_Output.md
> +2. [Ссылка](https://www.youtube.com/watch?v=R-a4zkZbPVo&list=PL0def37HEo5KMH7gONw_JnczvQJBv1EZL&index=20) на видеозапись лекции 2020 года.
Я использовал обе лекции при написании конспекта. Что-то для меня было понятнее в одной лекции, что-то в другой.

2023-10-01 08:37 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +2. [Ссылка](https://www.youtube.com/watch?v=R-a4zkZbPVo&list=PL0def37HEo5KMH7gONw_JnczvQJBv1EZL&index=20) на видеозапись лекции 2020 года.
> Я использовал обе лекции при написании конспекта. Что-то для меня было понятнее в одной лекции, что-то в другой.

Просто тогда было бы неплохо как-то сказать для каких параграфов лучше одну запись смотреть, для каких другую. Студент ведь не будет по своей воле смотреть в 2 раза больше материала.

2023-10-01 08:57 UTC, HepoH3 requested changes
В целом неплохо, я еще не по всему прошелся, но потихоньку вырисовывается хороший материал. Молодец!

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Отдельная шина для системы ввода-вывода подключена к центральному процессору.
Ты сразу с двух ног врываешься в какие-то плюсы, а человек ведь вообще не знает что такое система ввода-вывода, для чего она нужна и как работает, и почему отдельная шина — это плюс.

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Плюсы: отдельная система ввода-вывода (для нее может быть соблюдена своя специфика, например меньшие скорости, определенный интерфейс работы, который больше подходит под данные системы)
Что значит "отдельная система". Лекция посвящена системе ввода-вывода и у этой системы есть _отдельная система ввода-вывода_?

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Системы вводы-вывода имеют отдельную шину управляния, а шины адреса и данных совпадают с таковыми у памяти. (например x86)
Выдели эти элементы маркированного списка в отдельные параграфы (ну и переформулируй так, чтобы это были именно типы систем).
Потому что сейчас это все сливается и непонятно где ты описываешь плюсы с минусами (которые часто тоже идут в виде маркированных списков)

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Системы с выделенным адресным пространством:
Параграфы

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +В выделенном адресном пространстве ячейки памяти отделены от модулей ввода-вывода. То есть процессор имеет 2 шины. Одна направлена для памяти, другая для ввода-вывода.
см. рис. 1

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +JTAG — это четырехпроводной интерфейс, с помощью которого можно проверить правильно ли работает устройство. Его часто иcпользуют для отладки процессорной системы.
Здесь же (до объяснения ниже схем и работы JTAG-а) надо рассказать о принципе работы граничного сканирования

2023-10-01 08:57 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +1. Ввод-вывод с опросом.
параграфы

2023-10-01 09:16 UTC, MDamirM commented on Lectures/20. Input_Output.md
> +2. [Ссылка](https://www.youtube.com/watch?v=R-a4zkZbPVo&list=PL0def37HEo5KMH7gONw_JnczvQJBv1EZL&index=20) на видеозапись лекции 2020 года.
Каждый параграф, кроме RAID (он есть только в лекции 2021 года), - это смесь обеих лекций, поэтому сложно сказать какую лекцию смотреть в конкретном параграфе. Но в принципе в обеих лекциях говориться одно и то же, просто немного другими словами. Так что уберу лекцию 2020 года.

2023-10-01 09:38 UTC, HepoH3 commented
Сделай реквест ревью как закончишь, чтоб я не бежал сюда после каждого коммита. Реквест можно кинуть вот так:
![firefox_hi1CEAKZ9h](https://github.com/MPSU/APS/assets/17159587/15b45535-814d-41b2-8a24-783c6005802d)

И если что, там с предыдущего ревью еще остался один пункт не закрытый, обрати внимание.

2023-10-04 12:48 UTC, HepoH3 requested changes
Я думаю скоро с этой лекцией уже закончим, пару прогонов мб еще по мелочам всяким.

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Механизм граничного сканирования заключен в сдвиговом регистре (Boundary Scan), подключенном к ячейкам, помещенным между выводами микросхемы и ядром, и мультиплексоре который подключает в нужный моме
Механизм не может быть заключен в регистре.
boundary scan означает граничное сканирование, а не сдвиговый регистр

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +> *Системы ввода-вывода* — это комплекс обмена информацией с внешними устройствами.
```suggestion
> *Система ввода-вывода* — это комплекс обмена информацией с внешними устройствами.  
```

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Способы реализации систем ввода-вывода:
```suggestion
Системы ввода вывода различают по различным способам подключения к процессору.
```

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +### Система ввода-вывода подключена к центральному процессору с помощью отдельной от памяти шины.
```suggestion
### Система ввода-вывода подключена к центральному процессору с помощью отдельной шины.
```

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Плюсы: специализация под систему ввода-вывода (т.к. управление осуществляется по другой линии), остаются отдельные инструкции для работы с вводом-выводом.
Что означит "остаются"? Я понимаю, что у инструкции фиксированного размера ограниченное количество комбинаций значений и теоретически, места под новые инструкции может не хватит, но здесь ведь наоборот, речь идет о том, чтобы увеличить число разных инструкций.

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
>  ## Системы ввода-вывода
Формат для каждого типа системы:

Подзаголовок
Рисунок
Плюсы-минусы
Пример

Пример сделать в виде: Архитектуры, использующие данный тип подсистемы ввода-вывода

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Минусы: программисту сложнее разобраться в коде в ассемблере.
это минус семейства архитектур RISC в целом. Распиши почему такой тип подсистемы усугубляет эту проблему (что различать где операция с памятью а где периферия будет сложнее).

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
>  ## Адресное пространство
Опять же: что такое адресное пространство? Потом добавить "подсистемы ввода-вывода различаются и по организации адресного пространства" и потом уже подзаголовки

2023-10-04 12:48 UTC, HepoH3 commented on Lectures/20. Input_Output.md
>  При выделенном адресном пространстве можно разрабатывать систему ввода-вывода отдельно от памяти. В случае совместного этого не получится потому, что система ввода-вывода и память должны удовлетворят
почему это находится в подразделе систем с совмещенным адресным пространством?

2023-10-04 21:41 UTC, HepoH3 requested changes

2023-10-04 21:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +- Минусы: в адресном пространстве лежат и ячейки памяти и регистры модулей ввода-вывода, а поскольку процессору без разницы писать в память или писать в управляющие регистры модулей ввода-вывода, про
```suggestion
- Минусы: поскольку для доступа к регистрам модулей ввода-вывода используется та же шина, что и для доступа к памяти, процессор использует в обоих случаях одни и те же инструкции, что отрицательно сказывается на читаемости ассемблерного кода.
```

2023-10-04 21:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Системы ввода-вывода различают организации адресного пространства.
У систем ввода-вывода нет сознания, чтобы они могли что-либо различать. Я понимаю что это все придирки, но кто-то обязательно прочтет именно так.

2023-10-04 21:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
>  Пример системы с выделенным адресным пространством на рис. 1.
```suggestion
Пример системы с выделенным адресным пространством приведен на рис. 1.
```

2023-10-04 21:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Пример системы с совместным адресным пространством на рис. 3.
```suggestion
Пример системы с совместным адресным пространством приведен на рис. 3.
```

2023-10-04 21:41 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Граничное сканирование (Boundary Scan) — это способ тестирования микросхемы. Он заключается в том, что между каждой ножкой и ядром помещается ячейка памяти, эти ячейки соединяются как сдвиговый регис
Уже лучше, но надо связать последнее предложение с описанием использования сдвигового регистра. Вот этот переход через "таким образом" совсем не очевиден для человека, незнакомого с темой.

2023-10-05 09:51 UTC, HepoH3 requested changes
Я думаю, это последняя правка

2023-10-05 09:51 UTC, HepoH3 commented on Lectures/20. Input_Output.md
> +Граничное сканирование (Boundary Scan) — это способ тестирования микросхемы. Он заключается в том, что между каждой ножкой и ядром помещается ячейка памяти, эти ячейки соединяются как сдвиговый регис
Хорошо, но слишком часто используется существительное "ножка".

2023-10-05 12:43 UTC, HepoH3 approved these changes

2023-10-05 12:43 UTC, merged

2023-10-05 12:44 UTC, HepoH3 commented
Отлично, молодец!