Добавление 22 конспекта лекции
MPSU/exAPS pull request #208
Opened 2023-09-29 20:58 UTC by mormoroz

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Процессоры общего назначения - процессоры **x86**. Процессоры **x86** имеют архитектуру с полным набором команд, то есть поддерживает большое количество инструкций с разной шириной.
Процессоры общего назначения != процессоры x86, лектор подразумевал там запятую, а не тире в своей речи.
Не процессоры x86, а процессоры архитектуры x86

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Изучим его микроархитектуру. Она состоит из трех основных блоков: **подсистема памяти**, **Execution Engine**, **Front-end** (который является CISC оболочкой)
см. рис. 4, рисунок разместить под этим абзацем

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**_Front-end_** - состоит из **кеш-инструкции**. Из **кеш-памяти** за один такт считывается сразу 16 байт (количество инструкций зависит от того сколько они будут занимать байт). Из **кеш-памяти** ин
фронтенд не состоит из инструкции

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Выше мы рассмотрели одно ядро. **Coffee Lake** может иметь 4, 6 и 8 ядер (на рисунке ниже представлен 4-ядерный процессор). Здесь используется **кольцевая шина**, идея заключается в том, что она объе
Не надо писать на рисунке ниже, укажи конкретный номер рисунка.
Второе предложение сформулировано плохо, как будто субтитры из видео выгрузил и сюда воткнул.

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +* **ЦПУ (Центрально Процессорное Устройство)**
центральное

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +* **Чипсет** - он состоит из одной или двух микросхем (северного и южного моста). В современных процессорах северных мост стали встраивать в **ЦПУ**, так как через него процессор общается с памятью и
Про чипсет надо расписать подробнее. Не его встроили в процессор, так как он общается с памятью. А северный мост — это микросхема, которая... и потом уже написать что перенесли в процессор, чтобы ускорить общение с высокоскоростной шиной.

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +![](Pic/lec-22-8.png)
про bios в итоге не написано

2023-09-30 07:27 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Немного живого примера, чтобы вам не разбирать свой компьютер и не изучать где на материнской плате находится северный и южный мост - умная картинка.
на рис. <нумерацию надо починить> представлена иллюстрация расположения...

2023-09-30 07:28 UTC, HepoH3 commented
А, и еще: тире (—) и дефис (-) — это разные знаки, и в большинстве случаев надо в этом конспекте ставить тире.

2023-09-30 07:53 UTC, HepoH3 commented
Так все хорошо, после этих правок надо будет сосредоточиться на основном объекте лекции — разбора микроархитектуры intela, но пока давай причешим текст.

2023-09-30 19:43 UTC, mormoroz commented on Lectures/22. General purpose systems.md
> +Изучим его микроархитектуру. Она состоит из трех основных блоков: **подсистема памяти**, **Execution Engine**, **Front-end** (который является CISC оболочкой)
Вы хотите, чтобы перед началом описания каждого блока шёл рисунок этого блока? Или Вы имели ввиду, что после этого абзаца был рисунок всего Coffee Lake?

2023-10-01 08:59 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Изучим его микроархитектуру. Она состоит из трех основных блоков: **подсистема памяти**, **Execution Engine**, **Front-end** (который является CISC оболочкой)
Чтобы после этого абзаца был рисунок всего Coffee Lake, да. Ты ниже говоришь про всякие фронтенды, бэкэнды, а человек понятия не имеет о чем речь.

2023-10-01 09:00 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Выше мы рассмотрели одно ядро. **Coffee Lake** может иметь 4, 6 и 8 ядер (на рисунке 8 представлен 4-ядерный процессор). Подсистемы памяти каждого ядра объединяются в **кольцевую шину**.  **Кольцевая
Отлично, так гораздо лучше!

2023-10-01 09:00 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Как видно **северный мост** находится ближе к процессору, а **южный** к периферии, USB и т.п.
```suggestion
Обратите внимание на то, что **северный мост** находится ближе к процессору, а **южный** к периферии, USB и т.п. 
```

2023-10-01 09:17 UTC, HepoH3 requested changes

2023-10-01 09:17 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**_Front-end_** – **Кеш-инструкция** считывает из **кеш-памяти** за один такт сразу 16 байт (количество инструкций зависит от того сколько они будут занимать байт). Из **кеш-памяти** инструкции попад
Кэш-инструкция ничего не считывает (если это не инструкция загрузки конечно).

2023-10-01 09:17 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Изучим его микроархитектуру. Она состоит из трех основных блоков: **подсистема памяти**, **Execution Engine**, **Front-end** (который является CISC оболочкой)
Тут надо подробнее написать про составные части. Что значит "который является CISC-оболочкой"? Ориентируйся на студента, который не смотрел лекцию.

2023-10-01 09:17 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**_Front-end_** – **Кеш-инструкция** считывает из **кеш-памяти** за один такт сразу 16 байт (количество инструкций зависит от того сколько они будут занимать байт). Из **кеш-памяти** инструкции попад
Разбей этот огромный абзац на несколько поменьше, иначе это все сливается в нечитаемую стену текста. И каждый из блоков (фронтэнд, движок, подсистема памяти) должны быть выделены в отдельные абзацы

2023-10-01 09:17 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**_Execution Engine_** – получает инструкции в **ReOrder Buffer**, который переименовывает регистры, чтобы избежать конфликтов. Из блока **ReOrder Buffer** выходят микро инструкции с известными места
> известными местами куда будет сохранено

> где происходит диспетчеризация, т.е. инструкции раздаются на различные порты

надо переформулировать.

> На выходе каждого порта стоят функциональные блоки

Что это за блоки, зачем они стоят?

> Результаты этих блоков подключены к подсистеме **Memory Subsystem**

Я понимаю что про эту подсистему ты дальше напишешь, но надо либо тут хотя бы пару слов о ней сказать, либо написать "о которой рассказано в следующем параграфе.

Более того, не все эти блоки подключены к подсистеме памяти.

В конце этого абзаца надо поставить точку.

2023-10-04 13:01 UTC, HepoH3 requested changes
Так, еще раз прошелся по тексту пока время свободное было

2023-10-04 13:01 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Для начала мы повторим классифицирование микропроцессоров.
```suggestion
Для начала повторим классификацию микропроцессоров.
```

2023-10-04 13:01 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**Микропроцессоры общего назначения** – нужны для решения любых задач, он не предназначен для специализированных задач. Для них мы используем **специализированные микропроцессоры**.
```suggestion
**Микропроцессоры общего назначения** – нужны для решения любых задач, они не предназначен для специализированных задач. Для них мы используем **специализированные микропроцессоры**.
```

2023-10-04 13:01 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Процессоры архитектуры **x86** имеют архитектуру с полным набором команд, то есть поддерживает большое количество инструкций с разной шириной.
```suggestion
Процессоры архитектуры **x86** имеют архитектуру с полным набором команд, то есть поддерживают большое количество инструкций с разной шириной.
```

2023-10-04 13:01 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +</div>
Лучше сделать в виде markdown таблицы (после того как уйдет рис.2 необходимо поправить нумерацию)

2023-10-04 13:01 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +* **Чипсет** – он состоит из одной или двух микросхем (северного и южного моста).
Из чего состоит мы поняли, а что это такое?

2023-10-12 13:12 UTC, HepoH3 requested changes

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Изучим его микроархитектуру. Она состоит из трех основных блоков: **подсистема памяти**, **Execution Engine** (RISC процессор), **Front-end** (который является CISC оболочкой). То есть **Front-end**
```Markdown
Рассмотрим микроархитектуру процессора **Coffe Lake**, выпущенного в 2017-ом году. Она состоит из трех основных блоков:

- **Memory Subsystem** (подсистема памяти);
- **Execution Engine** (RISC-ядра);
- **Front-end** (CISC-оболочка поверх **Execution Engine**).

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +1. Из **кеш-памяти** за один такт считывается сразу 16 байт и попадают в блок **Instruction Fetch**, где определяется в каком порядке необходимо выполнять полученные инструкции (количество инструкций
Нумеровать список не обязательно, если это не прямо пронумерованная последовательность действий. Первый пункт не понятен, надо объяснить что CISC-инструкции могут быть разной длины, и поэтому неизвестно что будет в этих 16 байт — это может быть 2 инструкции, может быть кусок инструкции с предыдущих 16-и байт, может быть кусок инструкции которая не поместилась.

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +2. Из блока **Instruction Fetch** выходят до 6 макро-операций CISC инструкций в блок очереди инструкций, где благодаря **Macro-Fusion** некоторые инструкции объединяются (только если это допустимо).
Что значит объединяются, как это происходит? +2 -1 объединяются в +1?

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +3. Из **Instruction Queue** выходит 5 макро инструкций (с учётом того, что некоторые могли быть объеденины в одну), и попадают в **5-Way Decode (пяти секционный дешифратор)**.
а если они не были объединены в итоге? может ли быть такое, что пришло 6, и объединения не произошло?

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +4. **Пяти секционный дешифратор** преобразует макро операции CISC инструкции в RISC инструкции. Отсюда разные макро инструкции транслируются в разную последовательность микро инструкций (инструкции д
что такое "макро-операции CISC-инструкции"?

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +1.  **ReOrder Buffer** получает инструкции и переименовывает их регистры, чтобы избежать конфликтов. Из блока **ReOrder Buffer** выходят микро инструкции с известными адресами куда они будут сохранен
У инструкции нет регистров (нужно написать: используемые ими регистры). Распиши что значит "переименовывает".

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +2. В **Scheduler Unified Reservation Station** происходит диспетчеризация, то есть микро инструкции раздаются на различные порты. На выходе каждого порта стоят функциональные блоки (**EUs - Execution
"подсистеме Memory Subsytem" означает "подсистеме подсистемы памяти". Надо написать подсистеме памяти (Memory Subsystem). Про в следующем параграфе можно убрать.

2023-10-12 13:12 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Выйдем на уровень системы. То что мы смотрели в прошлых параграфах - **центрально процессорное устройство (CPU)**. Сейчас же мы разберём из чего в целом состоит компьютер:
я имел в виду не "что такое компьютер", а что такое "что такое чипсет" 😅

2023-10-21 09:58 UTC, HepoH3 reviewed
В общем почитай [эту страницу](https://en.wikichip.org/wiki/intel/microarchitectures/skylake#Front-end) и пройдись еще раз по оставшимся блокам. Я не могу за тебя это все делать.

2023-10-21 09:58 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Из **кеш-памяти** за один такт считывается сразу 16 байт CISC-инструкций. Они могут быть разной длины, поэтому неизвестно что будет в этих 16 байт — это может быть 2 инструкции, может быть кусок инст
Я просто приводил пример, это было не руководство к переписыванию.

```suggestion
Из **кеш-памяти** за один такт считывается сразу 16 байт CISC-инструкций, которые подаются в **Буфер предварительного декодирования** (**Instruction Fetch & PreDecode**). **x86**-инструкции сложны, имеют переменную длину, несогласованное кодирование и могут содержать несколько операций. Буфер предварительного декодирования выполняет разметку границ инструкций. Это довольно сложная задача, так как длина каждой инструкции может варьироваться от одного байта до пятнадцати. Кроме того, для определения длины может потребоваться просмотр нескольких первых её байт. Помимо разметки границ, декодируются префиксы инструкции, которые затем проверяются на различные свойства, например ветвления[\[1\]](https://en.wikichip.org/wiki/intel/microarchitectures/skylake#Front-end).
```

2023-10-21 09:58 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Из блока **Instruction Fetch** выходят до 6 макро-операций CISC инструкций (машинные инструкции x86) в блок очереди инструкций, где благодаря **Macro-Fusion** некоторые инструкции объединяются (то ес
```suggestion
Из блока **Буфера предварительного кодирования** выходят до 6 макро-операций, которые затем подаются в блок **очереди инструкций**, где (в некоторых случаях) благодаря **Macro-Fusion** две последовательно идущие инструкции могут быть преобразованы в одну. 

![firefox_gZFpG6RePR](https://github.com/MPSU/APS/assets/17159587/7ddfa5d3-5ece-4e34-a63f-24b6e225bdbb)

_Рисунок № . Пример объединения двух инструкций в блоке **Macro-Fusion**[\[2\]](https://en.wikichip.org/wiki/intel/microarchitectures/skylake#Instruction_Queue_.26_MOP-Fusion)_

За такт может произойти только одно подобное объединение. Иными словами, даже если в очереди окажется две пары подходящих для объединения инструкций, объединена будет только первая пара (кроме того, есть и другие ограничения по объединению)[\[3\]](https://en.wikichip.org/wiki/macro-operation_fusion#Mechanism).

Почему этап **Macro-Fusion** не может быть реализован на этапе компиляции программы? Дело в том, что в результате этого преобразования, результирующая макро-операция уже не является какой-то стандартной x86-инструкцией. Вместо этого, она становится какой-то специальной инструкцией, которая в дальнейшем может быть декодирована и исполнена только данной микроархитектурой процессора.

В наборе инструкций x86 нет операции условного перехода в том виде, в котором они представлены в ISA RISC-V. Вместо этого, условный переход делится на две инструкции:

- инструкция вычисления результата условия
- инструкция прыжка в зависимости от результата условия

Таким образом, каждый такой переход накладывает на процессор штраф в одну дополнительную инструкцию. При создании новых процессоров уже невозможно избавиться от этого штрафа через изменение существующей ISA x86 (из-за проблем с обратной совместимостью программ), именно поэтому и был создан данный блок[[\4\]](https://arxiv.org/pdf/1607.02318.pdf).
```

2023-10-21 09:58 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +Из **Instruction Queue** выходит 5 макро инструкций (с учётом того, что некоторые могли быть объеденины в одну, если такие инструкции были), и попадают в **5-Way Decode (пяти секционный дешифратор)**
```suggestion
Из **Instruction Queue** выходит 5 макро-инструкций (с учётом того, что две из шести инструкций могли быть объединены), и попадают в **5-Way Decode** (**пятисекционный дешифратор**).
```

2023-10-21 09:58 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**Пяти секционный дешифратор** преобразует макро операции CISC инструкции в RISC инструкции. Отсюда разные макро инструкции транслируются в разную последовательность микро инструкций (инструкции для
```suggestion
**Пяти секционный дешифратор** преобразует макро-операции в микро-операции (которые похожи на RISC-инструкции). Простые макро-операции попадают в **Simple Decoder** и преобразуются в одну микро-операцию. Более сложные попадают в **Complex Decoder**. Самые сложные макро-операции полагаются на память микропрограмм **MicroCode Sequencer** (где написана целая микропрограмма для исполнения конкретной макро-операции). Помимо прочего здесь подключен **Stack Engine** — аппаратный блок, позволяющий вычислять обновленное значение указателя на стек (без исполнения соответствующей микро-операции).

**Предсказатель результата ветвлений** (**Branch Predictor**) говорит о том какой адрес необходимо использовать для получения новых инструкций еще до вычисления результата ветвления.

**Буфер декодированного потока инструкций** (**Decoded Stream Buffer**) содержит декодированные ранее операции. В случае, если будут получены макро-операции, которые уже были недавно декодированы, данный буфер сможет сразу же выдать готовые микро-инструкции.
```

2023-10-21 09:58 UTC, HepoH3 commented on Lectures/22. General purpose systems.md
> +**BIOS** – базовая система ввода-вывода. С загрузки **BIOS** начинается включение компьютера: **BIOS** копирует свою программу в основную память и отдаёт её процессору управления, чтобы **ЦПУ** прове
```suggestion
Выйдем на уровень системы. Ранее мы рассматривали только Центральный Процессор (ЦП)**. Сейчас же мы разберём из чего в целом состоит компьютер:

- **Центральный процессор**
- **Генератор тактовых импульсов**
* **Чипсет** – набор микросхем, управляющих общением процессора, памяти и периферийных устройств. Обычно состоит из двух микросхем:
  - **Северный мост** — это контроллер-концентратор памяти, который взаимодействует с памятью и высокоскоростными устройствами `PCI-E`. Чтобы ускорить общение с высокоскоростной шиной в современных процессорах северных мост стали встраивать в **ЦП**.
  - **Южный мост** — контроллер-концентратор ввода-вывода, который связан с медленными устройствами (BIOS, PCI, SATA и т.п.).
- **BIOS** – базовая система ввода-вывода. С загрузки **BIOS** начинается включение компьютера: **BIOS** копирует свою программу в основную память, после чего передает управление процессору, чтобы тот проверил: какое оборудование подключено, как его необходимо сконфигурировать и в рабочем ли состоянии оно находится (т.е. сканирует и конфигурирует систему).
```

2023-11-04 08:32 UTC, HepoH3 approved these changes

2023-11-04 08:34 UTC, merged

2023-11-04 08:34 UTC, HepoH3 commented
Отлично, идем дальше