ПИН
MPSU/exAPS pull request #210
Opened 2023-10-01 21:23 UTC by Kholodhaha

Лекция 18. Синхронизация. Когерентность кеш.

2023-10-04 14:04 UTC, HepoH3 reviewed
Пока что методичка состоит из разрозненных кусков текста, которые тяжело читать.

2023-10-04 14:04 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Поток - это минимальная неделимая единица программы, которая может исполняться.
что значит "которая может исполняться"?

2023-10-04 14:04 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Поток - это минимальная неделимая единица программы, которая может исполняться.
"-" — это символ "дефис", который используется для соединения частей слов.
Тебе в данном случае нужно использовать символ "тире" (—)

2023-10-04 14:04 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +        * Неявная связь с помощью загрузки и сохранения в память
Что это за маркированный список и зачем он появился? Я не про то что его надо удалить, а про то что должен быть сопровождающий текст.

2023-10-04 14:04 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +![](https://sun9-75.userapi.com/impg/39UR2gW5QP8F3h_s-6dzk9vHIetvXpZViANxDg/KC_XlI12Gew.jpg?size=261x267&quality=96&sign=8cdd5e20544a4a1f3f66d1dce913afbd&type=album)
рисунки не подписаны и неясно как они связаны с текстом

2023-10-04 14:04 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Проиводитель-потребитель(producer-consumer): потребительский процесс должен ждать, пока процесс производителя не произведет данные (то есть потребитель не может быть запущен раньше, чем производите
```suggestion
* Проиводитель-потребитель (producer-consumer): потребительский процесс должен ждать, пока процесс производителя не произведет данные (то есть потребитель не может быть запущен раньше, чем производитель произведёт какие-то данные)
```

2023-10-05 13:07 UTC, HepoH3 requested changes

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +    * Несколько взаимодействующих последовательных потоков, который взаимодействуют друг с другом
То что здесь перечислено не является задачами. В лучшем случае это перечисление и оно не вяжется с элементом маркированного списка верхнего уровня.

Кстати, зачем выделять корень маркированного списка в виде элемента списка, у тебя ведь нет других элементов первого уровня? Этот же вопрос ко всем остальным спискам

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +   * Разделенное адресное пространство ( у каждого из процессоров своя память)
```suggestion
   * Разделенное адресное пространство (у каждого из процессоров своя память) 
```

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +   * Разделенное адресное пространство ( у каждого из процессоров своя память)
общая память и обмен сообщениями должны быть элементами одного уровня маркированного списка

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +### Синхронная связь
Здесь и во всем остальном документе: любой заголовок должен быть отделен от остальной части документа пустыми строками по обе стороны от него (ну, кроме начала документа).

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Метка loop указывает на последовательность инструкций <xxx<sub>1</sub>>, которые генерируют данные с. После этого производитель оправляет эти данные для потребителя и потом возвращается к началу цикл
```suggestion
Метка `loop` указывает на последовательность инструкций <xxx<sub>1</sub>>, которые генерируют данные `с`. После этого производитель оправляет эти данные для потребителя и потом возвращается к началу цикла и так далее. В свою очередь потребитель получает данные (receive) от производителя, выполняет над ними нужные операции и снова возвращается к началу цикла.
```

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Буфер Fifo ослабляет ограничения, связанные с синхронизацией. Производитель может опередить потребителя на N значений (где N — глубина данного буфера)
фифо — либо целиком капсом, либо целиком строчно

2023-10-05 13:07 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +У нас есть буфер на 3 элемента (то есть наша очередь), есть два указателя, один указывает на запись (write ptr), а другой указывает откуда мы её считываем (ride ptr).Допустим происходит генерация нов
В остальных частях документа сделай так же.

```suggestion
У нас есть буфер на 3 элемента (то есть наша очередь), есть два указателя, один указывает на запись (`write ptr`), а другой указывает откуда мы её считываем (`ride ptr`). Допустим происходит генерация новых данных (`send c₀`), они записываются по нашему указателю, после этого указатель сдвигается на одну ячейку вправо (`i+1`), затем происходит то же самое и по итогу указатель сдвинулся по кругу. Далее забираем наши данные (происходит `rcv()`), теперь указатель `ride ptr` смещается вправо и так далее.
```

2023-10-12 14:02 UTC, HepoH3 requested changes
Я понимаю, материала довольно много, проделан большой объем работы, но это не значит, что можно жертвовать качеством. Раз уж начали, давай доводить до конца.

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +**Параллелизм уровня потоков** — это разделение вычеслений между несколькими исполнительными потоками, которые могут быть:
```suggestion
**Параллелизм уровня потоков** — это разделение вычислений между несколькими исполнительными потоками, которые могут быть:
```

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Существует две основные коммуникационные модели:
Существуют две модели

- Память
- Обмен

и потом в отдельных подзаголовках

### Общая память

....


### Обмен

....

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Например, дальше есть событие, которое будет использовать результаты вычеслений P<sub>1 </sub> и P<sub>2 </sub>. Только когда будут выполнены оба процесса может происходить дальнейшее выполнение, а з
Где "дальше"?

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> + **Взаимное исключение**: операционная система должна гарантировать, что ресурс используется только одним процессом в данный момент времени (например, не могут два процесса одновременно обращаться к
```suggestion
 **Взаимное исключение**: операционная система должна гарантировать, что ресурс используется только одним процессом в данный момент времени (например, два процесса не могут одновременно обращаться к одной ячейке памяти)
```

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Каждый поток выполняется некоторое время (прерывание по таймеру), а затем ОС переключается на другой поток, неоднократно
прерывание по таймеру — это не выполнение потока в течении какого-то времени

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +![](https://sun9-24.userapi.com/impg/9oNMOtZP4mznzi4S_Rtt62ZK5RdKhG_Mka0-8Q/Ennp4wm4xyA.jpg?size=439x418&quality=95&sign=82c81d8c36020df3af49e35bd79011fc&type=album)
Используй пикчи из презы, а не скрины из видоса. Ссылка на презы давалась в чате.

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +У нас есть буфер на 3 элемента (то есть наша очередь), есть два указателя, один указывает на запись (`write ptr`), а другой указывает откуда мы её считываем (`ride ptr`). Допустим происходит генераци
```suggestion
У нас есть буфер на 3 элемента (очередь) и два указателя: один указывает на место, куда мы будем писать (`write_ptr`), а другой указывает на место, откуда мы будем читать (`read_ptr`). В очередной момент времени происходит генерация новых данных (`send c<sub>0</sub>`) — они записываются в место, куда указывает `write_ptr`. После этого данный указатель сдвигается на одну ячейку вправо (`i+1`).
```

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +У нас есть буфер на 3 элемента (то есть наша очередь), есть два указателя, один указывает на запись (`write ptr`), а другой указывает откуда мы её считываем (`ride ptr`). Допустим происходит генераци
Удаленная часть в конце — это то что я вообще не понял, перепиши ее.

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Данный буфер **не применяет никаких ограничений приоритета** (_например, `rcv()` может быть вызван до любой отправки_), поэтому и работает неправильно. Чтобы устранить эту проблему, нам поможет конце
где вообще по тексту выше говорилось, что что-то "работает неправильно"?

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* `signal` (`semaphore s`) - `s` = `s` + 1 (один ожидающий поток теперь может быть в состоянии продолжить)
Что это за маркированный список: "Новый тип данных" / "Новые операции"? Ты не новый класс в очередном аддоне WoW анонсируешь. Свяжи это как-то с текстом.

2023-10-12 14:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +`signal(s)<sub>i</sub>` < `wait(s)<sub>i+K</sub>`,`i`-ый вызов `signal(s)` должен завершиться до завершения `(i+K)` вызова `wait(s)`
посмотри как рендерится, надо исправить (здесь и в остальном тексте)

2023-10-21 13:10 UTC, HepoH3 reviewed
Там еще с предыдущих ревью незакрытые замечания остались если что

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Обща память
```suggestion
* Общая память
```

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Необходимость в синхронизации возникает каждый раз, когда в системе существуют параллельные процессы
Вот у тебя два заголовка третьего уровня: "Общая память" и "обмен сообщениями". И сразу после них идет "Синхронизация (пам-парам)" этот параграф идет под заголовком третьего уровня, потому что это продолжение заголовка второго уровня? Т.е. ты пропустил Синхронизацию в маркированном списке, когда писал про "две основные коммуникационные модели:"?

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +*Рис. 3. Вилки и соединения (fork and join).*
Способ синхронизации параллельных процессов "Вилки и соединения".

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +*Рис. 4. Проиводитель-потребитель (producer-consumer).
тоже самое

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Каждый поток выполняется некоторое время (прерывание по таймеру), а затем ОС переключается на другой поток, неоднократно
и что за "неоднократно" в конце? и не забывай ставить на протяжении всего текста точки

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Метка `loop` указывает на последовательность инструкций xxx₁, которые генерируют данные `с`. После этого производитель оправляет эти данные для потребителя и потом возвращается к началу цикла и так д
```suggestion
Метка `loop` указывает на последовательность инструкций xxxᵢ, которые генерируют данные `с`. После этого производитель оправляет эти данные для потребителя и потом возвращается к началу цикла и так далее. В свою очередь потребитель получает данные (receive) от производителя, выполняет над ними нужные операции и снова возвращается к началу цикла.
```

2023-10-21 13:10 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Данный буфер **не применяет никаких ограничений приоритета** (_например, `rcv()` может быть вызван до любой отправки_), поэтому и работает неправильно. Чтобы устранить эту проблему, нам поможет конце
```suggestion
Данный буфер **не применяет никаких ограничений приоритета** (_например, `rcv()` может быть вызван до любой отправки_) и поэтому работает неправильно. Чтобы устранить эту проблему, нам поможет концепция _семафоров_.
```

2023-10-21 14:06 UTC, Kholodhaha commented on Lectures/18. Synchronization. Cache coherence.md
> +Необходимость в синхронизации возникает каждый раз, когда в системе существуют параллельные процессы
Синхронизация не относится к основным потокам коммуникационной модели. Однако в лекции она идёт до блока "Потоково-безопасное программирование", а значит относится к блоку "Параллелизм уровня потоков", при этом является важной подтемой, поэтому и является подзаголовком третьего уровня, не понимаю вашего замечания тут. Могу сделать "синхронизацию" подзаголовком 4-ого уровня, но мне кажется это странным.

2023-10-21 14:11 UTC, Kholodhaha commented on Lectures/18. Synchronization. Cache coherence.md
> +*Рис. 4. Проиводитель-потребитель (producer-consumer).
На счёт точек.Открыл для примера лекцию 8 с гита с ветки ПИН. Точки стоят в разных местах, как понять, когда тут ставить точки? В конце любого предложения? Или в конце любого предложения если не идёт пересечение через список?
![image](https://github.com/MPSU/APS/assets/116362016/ed3d4aeb-ad72-4523-a684-8c3a6f5b0b6c)

2023-10-21 14:12 UTC, Kholodhaha commented on Lectures/18. Synchronization. Cache coherence.md
> +* `signal` (`semaphore s`) - `s` = `s` + 1 (один ожидающий поток теперь может быть в состоянии продолжить)
Можете пояснить более понятно, пожалуйста. Не играл в WoW и темболее не знаю как выглядит там аддон

2023-10-21 14:15 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Необходимость в синхронизации возникает каждый раз, когда в системе существуют параллельные процессы
Тогда должно быть какое-то логическое завершение после обмена сообщений, чтобы следующий абзац не сливался с предыдущими, должен быть какой-то текст после которого становится понятно: "ага, к с этим закончили". Конспект — это ведь не вертикальное представление слайдов с презы, связующее звено слайдов — голос за кадром, который здесь должен заменять твой собственный текст какой-то.

2023-10-21 14:26 UTC, Kholodhaha commented on Lectures/18. Synchronization. Cache coherence.md
> +* Каждый поток выполняется некоторое время (прерывание по таймеру), а затем ОС переключается на другой поток, неоднократно
а как тогда лучше написать здесь? вот скрин с видео лектора, он это просто читает эти строки, не добавляя никаких других комментариев, я переписал отсюда один в один...
![image](https://github.com/MPSU/APS/assets/116362016/3fc7bd9d-5a7f-4e91-a292-3b1bb6dd9faa)

2023-10-21 14:35 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Каждый поток выполняется некоторое время (прерывание по таймеру), а затем ОС переключается на другой поток, неоднократно
Еще раз, презы лектора не являются эталоном, который нужно сюда пергнать, там (как в презах, так и в некоторых утверждениях на лету) могут быть и ошибки. Именно поэтому важно сделать конспекты — их в отличие от записи лекции всегда можно быстро исправить.

Касательно вопроса, я бы написал например вот так:

Многопоточные программы могут выполняться на одном процессоре с помощью таймшеринга, смысл которого заключается в том, что каждый поток выполняется некоторое время (например до очередного прерывания по таймеру), после чего ОС переключается на другой поток и все повторяется заново.

2023-10-28 10:39 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Вилки и соединения (fork and join): параллельный процесс может подождать, пока не произойдёт несколько событий
может или должен?

2023-10-28 10:39 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
>  То есть в рамках одной задачи может быть несколько потоков, они могут либо конкурировать за общие ресурсы, либо дожидаться друг друга, требовать синхронизации
```suggestion
* несколькими независимыми последовательными потоками, которые конкурируют за общие ресурсы, такие как память, устройства ввода/вывода;
* несколькими взаимодействующими последовательными потоками, которые взаимодействуют друг с другом.

То есть в рамках одной задачи может быть несколько потоков, они могут либо конкурировать за общие ресурсы, либо дожидаться друг друга, требовать синхронизации.
```

2023-10-28 10:39 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +Например, в системе есть событие, которое будет использовать результаты вычеслений `P₁` и `P₂`. Только когда будут выполнены оба процесса может происходить дальнейшее выполнение, а значит есть необхо
```suggestion
Рассмотрим ситуацию, когда процесс порождает два параллельных потока `P₁` и `P₂` и впоследствии использует результаты их вычислений. После создания, процесс сможет продолжить дальнейшее выполнение только когда будут выполнены оба потока, а значит есть необходимость их синхронизировать.
```

2023-10-28 10:39 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
>  * Проиводитель-потребитель (producer-consumer): потребительский процесс должен ждать, пока процесс производителя не произведет данные (то есть потребитель не может быть запущен раньше, чем производит
Он может быть запущен раньше. Просто он должен именно **ждать** (не может продолжить исполнение).

2023-10-28 10:39 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +![](https://sun9-24.userapi.com/impg/9oNMOtZP4mznzi4S_Rtt62ZK5RdKhG_Mka0-8Q/Ennp4wm4xyA.jpg?size=439x418&quality=95&sign=82c81d8c36020df3af49e35bd79011fc&type=album)
Зачем вообще кстати рис7, если это плохой дубликат рис6?

2023-10-28 10:45 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* `signal` (`semaphore s`) - `s` = `s` + 1 (один ожидающий поток теперь может быть в состоянии продолжить)
Я говорю о подаче. Что за "Новый тип данных", тем более в виде маркированного списка? Новый относительно чего? Не важно анонс чего это, WoW, нового айфона или процессора intel, ты же видел рекламу когда-нибудь?

Вот в рекламе говорят именно так: 

в новой модели <что-нибудь> появились:

* Новый тип данных: semaphore, число ≥ 0
* semaphore `s` = `K`; // инициализируем `s` значением `K`

Новые операции: (определены для симофоров)
* `wait` (` semaphore s`) - ждёт если `s` == 0, после чего `s` = `s` - 1
* `signal` (`semaphore s`) - `s` = `s` + 1 (один ожидающий поток теперь может быть в состоянии продолжить)

---

Однако по тексту не очень понятно, что ты рекламируешь, ведь нет даже продукта, относительно которого появились эти "новые типы и операции".

2023-10-28 10:49 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +*Рис. 4. Проиводитель-потребитель (producer-consumer).
> На счёт точек.Открыл для примера лекцию 8 с гита с ветки ПИН. Точки стоят в разных местах, как понять, когда тут ставить точки? В конце любого предложения? Или в конце любого предложения если не идёт пересечение через список? ![image](https://user-images.githubusercontent.com/116362016/277112724-ed3d4aeb-ad72-4523-a684-8c3a6f5b0b6c.png)

Точки надо ставить в конце любого предложения кроме заголовков. Если идет маркированный список, который является перечислением (перед списком идет текст с двоеточием в конце), то после каждого элемента списка ставится точка с запятой, в конце последнего элемента — точка. Элементы списка при этом пишутся со строчных букв.

Исключением являются списки, в которых элементы состоят из нескольких предложений. В этом случае приходится делать некрасиво, и ставить точки в конце каждого элемента, а сами элементы начинать с заглавной буквы.

2023-10-28 10:54 UTC, HepoH3 reviewed
По поводу уровней заголовков.

Сначала идет Параллелизм уровня потоков заголовком второго уровня, потом идут общая память и обмен сообщениями заголовками третьего уровня. Потом необходимо рассказать, что общая память делается проще, но страдает от гонок, в то время как сообщения сложнее, но без гонок. Дальше мы сосредоточимся на общей памяти и обсудим как происходит синхронизация.

После этого идет заголовок второго уровня Синхронизация.

Вот [лекция](https://www.youtube.com/watch?v=JzzE7W3ZPXw), которая лежит в основе первой половине лекции Михаила Геннадьевича. Посмотри как она там рассказывает эти слайды и как происходит переход, вот тебе нужно так и описать.

2023-11-04 10:02 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +* Проиводитель-потребитель (producer-consumer): потребительский процесс должен ждать, пока процесс производителя не произведет данные (то есть потребитель не может быть запущен раньше, чем производит
```suggestion
* Проиводитель-потребитель (producer-consumer): потребительский процесс должен ждать, пока процесс производителя не произведет данные (то есть потребитель не может продолжать выполнение, пока производитель не произведёт какие-то данные).
```

2023-11-04 10:03 UTC, HepoH3 commented
> По поводу уровней заголовков.
> 
> Сначала идет Параллелизм уровня потоков заголовком второго уровня, потом идут общая память и обмен сообщениями заголовками третьего уровня. Потом необходимо рассказать, что общая память делается проще, но страдает от гонок, в то время как сообщения сложнее, но без гонок. Дальше мы сосредоточимся на общей памяти и обсудим как происходит синхронизация.
> 
> После этого идет заголовок второго уровня Синхронизация.
> 
> Вот [лекция](https://www.youtube.com/watch?v=JzzE7W3ZPXw), которая лежит в основе первой половине лекции Михаила Геннадьевича. Посмотри как она там рассказывает эти слайды и как происходит переход, вот тебе нужно так и описать.

Все, сделай как тут сказано и на этом заканчиваем.

2023-11-04 12:56 UTC, HepoH3 commented
А, и у тебя нумерация пикч съехала после удаления седьмой.

2023-11-11 19:33 UTC, HepoH3 commented on Lectures/18. Synchronization. Cache coherence.md
> +В плане реализации коммуникационная модель с общей памятью намного проще нежели коммуникационная модель с обменом сообщениями. Однако первая модель в отличие от второй страдает от того, что различные
```suggestion
В плане реализации коммуникационная модель с общей памятью намного проще нежели коммуникационная модель с обменом сообщениями. Однако у первой модели существует риск возникновения гонок, в связи с чем требуется осуществлять синхронизацию.
```

2023-11-11 19:33 UTC, merged